#ifndef __FAKEYAUL_MIC3D_SIZES_H__
#define __FAKEYAUL_MIC3D_SIZES_H__


#define STRUCT_MIC3D_SORT_SINGLES_BYTE_SIZE		2
#define STRUCT_MIC3D_CMDTS_BYTE_SIZE			32
#define STRUCT_MIC3D_DEPTH_VALUES_BYTE_SIZE		4
#define STRUCT_MIC3D_Z_VALUES_BYTE_SIZE			2
#define STRUCT_MIC3D_SCREEN_POINTS_BYTE_SIZE	4
#define STRUCT_MIC3D_RENDER_MATRICES_BYTE_SIZE	48
#define STRUCT_MIC3D_LIGHT_MATRICES_BYTE_SIZE	36
#define STRUCT_MIC3D_COLORS_BYTE_SIZE			2
#define STRUCT_MIC3D_WORK_BYTE_SIZE				80


#endif
